[package]
name = "binary-reader"
version = "0.4.5"
authors = ["MPThLee <mpthlee@gmail.com>"]
publish = true

description = "A binary reader for rust-lang. for step by step. It's a minimal `byteorder` wrapper for read bytes."
readme = "README.md"
license = "MIT"
repository = "https://github.com/MPThLee/binary-reader.rs"
keywords = ["binary", "reader", "byteorder"]

# Rust version.
edition="2018"

# Abort instead of panic, Since it doesn't need panic in this library.
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
byteorder = "~1.4.3"

[dev-dependencies]
# Pretty Assertions should not be over 1.3.0 as its MSRV is 1.54.0.
# Yes, It's pretty old. But this libary follows byteorder's MSRV only. (Rust 1.14.1 - Released on Feb 27, 2020) 
pretty_assertions = "~1.2.1"