name: Coverage test

on: [push, pull_request]

jobs:
  test:
    name: Coverage test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --tests --doc --examples --exclude-files=examples/*.rs --no-fail-fast --timeout 240 --out Xml 

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true
