name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: |
          cargo package
          cargo publish --token ${{ secrets.CARGO_TOKEN }}
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release gh-release
        uses: softprops/action-gh-release@v1